Don't assume we can create a folder named after the module.
Running mockbuild on the ht2html Fedora package fails with the following
cryptic error:
State Changed: init
ERROR: Could not create dir
/path/to/clone/ht2html/ht2html/2.0/12.fc17. Error: [Errno 20] Not a directory: '/path/to/clone/ht2html/ht2html/2.0'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 61, in mkdirIfAbsent
    os.makedirs(dirName)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 20] Not a directory: '/path/to/clone/ht2html/ht2html/2.0'
ERROR: Exception(/path/to/clone/ht2html/ht2html-2.0-12.fc17.src.rpm) Config(fedora-rawhide-x86_64) 0 minutes 0 seconds

What this means is that rpkg tries to create a folder named ht2html and
use it as its mock resultdir, but a file called ht2html already exists
inside the cloned git tree.

This could happen for other packages as well, so calling the folder with
a less obvious name should make conflicts much less likely.